runtime: custom
vm: true

# [START entrypoint]
#entrypoint: gunicorn -b :$PORT main:app
entrypoint: honcho start -f procfile app
# [END entrypoint]

health_check:
  enable_health_check: False

runtime_config:
  python_version: 2

