service: default
runtime: custom
vm: true

# [START entrypoint]
entrypoint: honcho start -f procfile app
# [END entrypoint]

health_check:
  enable_health_check: False

runtime_config:
  python_version: 2

handlers:
- url: /.*
  script: IGNORED
  secure: always
- url: /cleanup/storage
  login: admin

